src/django_quotes/urls.py
#
# urls.py
#
# Copyright (c) 2024 Daniel Andrlik
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

"""Url patterns for application."""

from django.urls import path

from django_quotes.views import (
    QuoteCreateView,
    QuoteDeleteView,
    QuoteDetailView,
    QuoteListView,
    QuoteUpdateView,
    SourceCreateView,
    SourceDeleteView,
    SourceDetailView,
    SourceGroupCreateView,
    SourceGroupDeleteView,
    SourceGroupDetailView,
    SourceGroupListView,
    SourceGroupUpdateView,
    SourceListView,
    SourceUpdateView,
)

app_name = "quotes"
urlpatterns = [
    path("groups/", view=SourceGroupListView.as_view(), name="group_list"),
    path("groups/create/", view=SourceGroupCreateView.as_view(), name="group_create"),
    path(
        "groups/<slug:group>/",
        view=SourceGroupDetailView.as_view(),
        name="group_detail",
    ),
    path(
        "groups/<slug:group>/edit/",
        view=SourceGroupUpdateView.as_view(),
        name="group_update",
    ),
    path(
        "groups/<slug:group>/delete/",
        view=SourceGroupDeleteView.as_view(),
        name="group_delete",
    ),
    path(
        "groups/<slug:group>/sources/",
        view=SourceListView.as_view(),
        name="source_list",
    ),
    path(
        "groups/<slug:group>/sources/add/",
        view=SourceCreateView.as_view(),
        name="source_create",
    ),
    path(
        "sources/<slug:source>/",
        view=SourceDetailView.as_view(),
        name="source_detail",
    ),
    path(
        "sources/<slug:source>/edit/",
        view=SourceUpdateView.as_view(),
        name="source_update",
    ),
    path(
        "sources/<slug:source>/delete/",
        view=SourceDeleteView.as_view(),
        name="source_delete",
    ),
    path(
        "sources/<slug:source>/quotes/",
        view=QuoteListView.as_view(),
        name="quote_list",
    ),
    path(
        "sources/<slug:source>/quotes/add/",
        view=QuoteCreateView.as_view(),
        name="quote_create",
    ),
    path("quotes/<int:quote>/", view=QuoteDetailView.as_view(), name="quote_detail"),
    path("quotes/<int:quote>/edit/", view=QuoteUpdateView.as_view(), name="quote_update"),
    path(
        "quotes/<int:quote>/delete/",
        view=QuoteDeleteView.as_view(),
        name="quote_delete",
    ),
]

src/django_quotes/api/views.py
#
# views.py
#
# Copyright (c) 2024 Daniel Andrlik
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

from django.core.exceptions import ObjectDoesNotExist
from drf_spectacular.utils import extend_schema, inline_serializer
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.fields import CharField
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rules.contrib.rest_framework import AutoPermissionViewSetMixin

from django_quotes.api.serializers import (
    QuoteSerializer,
    SourceGroupSerializer,
    SourceSerializer,
)
from django_quotes.models import Source, SourceGroup


class SourceGroupViewSet(AutoPermissionViewSetMixin, RetrieveModelMixin, ListModelMixin, GenericViewSet):
    """
    A generic viewset for listing and retrieving details on sourceGroup groups.
    """

    serializer_class = SourceGroupSerializer
    lookup_field = "slug"
    lookup_url_kwarg = "group"
    permission_type_map = {
        "create": "add",
        "destroy": "delete",
        "list": None,
        "partial_update": "change",
        "retrieve": "read",
        "update": "change",
        "get_random_quote": "read",
        "generate_sentence": "read",
    }

    def get_queryset(self, *args, **kwargs):
        return SourceGroup.objects.filter(owner=self.request.user) | SourceGroup.objects.filter(  # type: ignore
            public=True
        )

    @extend_schema(responses={200: QuoteSerializer})
    @action(detail=True, methods=["get"])
    def get_random_quote(self, request, group=None):
        g = self.get_object()
        quote = g.get_random_quote()
        if quote is not None:
            qs = QuoteSerializer(quote)
            return Response(status=status.HTTP_200_OK, data=qs.data)
        return Response(status=status.HTTP_404_NOT_FOUND, data={"error": "No quotes found."})

    @extend_schema(responses={200: inline_serializer(name="generated_sentence", fields={"sentence": CharField()})})
    @action(detail=True, methods=["get"])
    def generate_sentence(self, request, group=None):
        g = self.get_object()
        if g.markov_sources == 0:
            return Response(
                status=status.HTTP_403_FORBIDDEN,
                data={"error": "This group does not currently allow sentence generation."},
            )
        sentence = g.generate_markov_sentence()
        if sentence is not None:
            return Response(status=status.HTTP_200_OK, data={"sentence": sentence})
        return Response(
            status=status.HTTP_204_NO_CONTENT,
            data={"error": "Insufficent data to generate sentence."},
        )


class SourceViewSet(AutoPermissionViewSetMixin, RetrieveModelMixin, ListModelMixin, GenericViewSet):
    """
    Retrieve and list views for sources.
    """

    serializer_class = SourceSerializer
    lookup_field = "slug"
    lookup_url_kwarg = "source"
    permission_type_map = {
        "create": "add",
        "destroy": "delete",
        "list": None,
        "partial_update": "change",
        "retrieve": "read",
        "update": "change",
        "get_random_quote": "read",
        "generate_sentence": "read",
    }

    def get_queryset(self, *args, **kwargs):
        group_slug = self.request.query_params.get("group")  # type: ignore
        queryset = Source.objects.filter(owner=self.request.user) | Source.objects.filter(public=True)  # type: ignore
        if group_slug:
            try:
                group = SourceGroup.objects.get(slug=group_slug)
            except ObjectDoesNotExist:
                return SourceGroup.objects.none()
            queryset = queryset.filter(group=group)
        return queryset

    @extend_schema(responses={200: QuoteSerializer})
    @action(detail=True, methods=["get"])
    def get_random_quote(self, request, source=None):
        source = self.get_object()
        quote = source.get_random_quote()
        if quote is not None:
            qs = QuoteSerializer(quote)
            return Response(status=status.HTTP_200_OK, data=qs.data)
        return Response(status=status.HTTP_404_NOT_FOUND, data={"error": "No quotes found."})

    @extend_schema(responses={200: inline_serializer(name="generated_sentence", fields={"sentence": CharField()})})
    @action(detail=True, methods=["get"])
    def generate_sentence(self, request, source=None):
        source = self.get_object()
        if not source.allow_markov:
            return Response(
                status=status.HTTP_403_FORBIDDEN,
                data={"error": "This source does not permit sentence generation."},
            )
        sentence = source.get_markov_sentence()
        if sentence is not None:
            return Response(status=status.HTTP_200_OK, data={"sentence": sentence})
        return Response(
            status=status.HTTP_204_NO_CONTENT,
            data={"error": "Unable to generate markov sentence. This source may not have enough quotes yet."},
        )

src/django_quotes/views.py
#
# views.py
#
# Copyright (c) 2024 Daniel Andrlik
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

from typing import TYPE_CHECKING

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView as GenericDetail
from django.views.generic import ListView as GenericList
from django.views.generic.edit import CreateView as GenericCreate
from django.views.generic.edit import DeleteView as GenericDelete
from django.views.generic.edit import UpdateView as GenericUpdate
from rules.contrib.views import PermissionRequiredMixin

from django_quotes.models import Quote, Source, SourceGroup

# Create your views here.


# SOURCE GROUPS


class SourceGroupListView(LoginRequiredMixin, GenericList):
    """
    Displays Source Groups owned by the user.
    TODO: For now, only user owned groups, we won't bother with public options.

    Available at /groups/
    """

    model = SourceGroup
    context_object_name = "groups"
    template_name = "quotes/group_list.html"
    paginate_by = 15
    allow_empty = True

    def get_queryset(self):
        return SourceGroup.objects.filter(owner=self.request.user)  # type: ignore


class SourceGroupDetailView(LoginRequiredMixin, PermissionRequiredMixin, GenericDetail):
    """
    Displays details for a source group.

    Available at /groups/[group_slug]/
    """

    model = SourceGroup
    context_object_name = "group"
    template_name = "quotes/group_detail.html"
    permission_required = "django_quotes.read_sourcegroup"
    slug_url_kwarg = "group"
    prefetch_related = ["source_set"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["source_sample"] = Source.objects.filter(group=context["group"])[:5]
        return context


class SourceGroupUpdateView(LoginRequiredMixin, PermissionRequiredMixin, GenericUpdate):
    """
    Update an existing source group

    Available at /groups/[group_slug]/edit/
    """

    if TYPE_CHECKING:
        object: SourceGroup

    model = SourceGroup
    context_object_name = "group"
    template_name = "quotes/group_update.html"
    permission_required = "django_quotes.edit_sourcegroup"
    fields = ["name", "description", "public"]
    slug_url_kwarg = "group"

    def get_success_url(self):
        messages.success(self.request, _(f"Successfully updated group {self.object.name}!"))
        return reverse_lazy("quotes:group_detail", kwargs={"group": self.object.slug})


class SourceGroupDeleteView(LoginRequiredMixin, PermissionRequiredMixin, GenericDelete):  # type: ignore
    """
    Delete and existing source group.

    Available at /groups/[group_slug]/delete/
    """

    model = SourceGroup
    context_object_name = "group"
    template_name = "quotes/group_delete.html"
    permission_required = "django_quotes.delete_sourcegroup"
    slug_url_kwarg = "group"
    success_url = reverse_lazy("quotes:group_list")


class SourceGroupCreateView(LoginRequiredMixin, GenericCreate):
    """
    Create a new source group.

    Available at /groups/create/
    """

    model = SourceGroup
    template_name = "quotes/group_create.html"
    fields = ["name", "description", "public"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        obj = form.save()
        messages.success(self.request, _(f"Successfully created group {obj.name}"))
        return HttpResponseRedirect(redirect_to=reverse_lazy("quotes:group_detail", kwargs={"group": obj.slug}))


# SOURCES


class SourceCreateView(LoginRequiredMixin, PermissionRequiredMixin, GenericCreate):
    """
    Create a new source and add them to a source group.

    Available at /groups/[group_slug]/sources/add/
    """

    model = Source
    template_name = "quotes/source_create.html"
    fields = ["name", "description", "allow_markov", "public"]
    permission_required = "django_quotes.edit_sourcegroup"
    group = None

    def dispatch(self, request, *args, **kwargs):
        group_slug = kwargs.pop("group")
        self.group = get_object_or_404(SourceGroup, slug=group_slug)
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.group

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["group"] = self.group
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.group = self.group
        obj = form.save()
        messages.success(self.request, _(f"Successfully created source {obj.name}!"))
        return HttpResponseRedirect(redirect_to=reverse_lazy("quotes:source_detail", kwargs={"source": obj.slug}))


class SourceDetailView(LoginRequiredMixin, PermissionRequiredMixin, GenericDetail):
    """
    Shows information about the specified source.

    Available at /groups/[group_slug]/sources/[source_slug]/
    """

    model = Source
    slug_url_kwarg = "source"
    slug_field = "slug"
    template_name = "quotes/source_detail.html"
    context_object_name = "source"
    permission_required = "django_quotes.read_source"
    prefetch_related = "quote_set"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["samp_quotes"] = context["source"].quote_set.all()[:5]
        return context


class SourceUpdateView(LoginRequiredMixin, PermissionRequiredMixin, GenericUpdate):
    """
    Allows editing and updating of a Source.

    Available at /groups/[group_slug]/sources/[source_slug]/edit/
    """

    model = Source
    slug_url_kwarg = "source"
    slug_field = "slug"
    template_name = "quotes/source_update.html"
    permission_required = "django_quotes.edit_source"
    fields = ["name", "description", "public", "allow_markov"]

    def get_success_url(self):
        messages.success(self.request, "Successfully updated source!")
        return reverse_lazy("quotes:source_detail", kwargs={"source": self.kwargs["source"]})


class SourceDeleteView(LoginRequiredMixin, PermissionRequiredMixin, GenericDelete):  # type: ignore
    """
    Used to delete a given Source

    Available at /groups/[group_slug]/sources/[source_slug]/delete/
    """

    model = Source
    slug_field = "slug"
    slug_url_kwarg = "source"
    template_name = "quotes/source_delete.html"
    permission_required = "django_quotes.delete_source"
    context_object_name = "source"

    def dispatch(self, request, *args, **kwargs):
        source_slug = kwargs.get("source")
        source = get_object_or_404(Source, slug=source_slug)  # type: ignore
        self.group = source.group
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("quotes:source_list", kwargs={"group": self.group.slug})


class SourceListView(LoginRequiredMixin, PermissionRequiredMixin, GenericList):
    """
    Display a list of sources for a given group.

    Available at /groups/[group_slug]/sources/
    """

    model = Source
    template_name = "quotes/source_list.html"
    permission_required = "django_quotes.read_sourcegroup"
    context_object_name = "sources"
    paginate_by = 15
    allow_empty = True
    group = None

    def dispatch(self, request, *args, **kwargs):
        group_slug = kwargs.pop("group")
        self.group = get_object_or_404(SourceGroup, slug=group_slug)
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.group

    def get_queryset(self):
        return (
            Source.objects.filter(group=self.group)
            .select_related("group", "owner")
            .prefetch_related("quote_set")
            .order_by("name")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["group"] = self.group
        return context


# QUOTES


class QuoteListView(LoginRequiredMixin, PermissionRequiredMixin, GenericList):
    """
    View for viewing quotes from a specific source.

    Available at /groups/[group_slug]/sources/[source_slug]/quotes/
    """

    model = Quote
    context_object_name = "quotes"
    template_name = "quotes/quote_list.html"
    permission_required = "django_quotes.read_source"
    paginate_by = 15
    allow_empty = True
    source = None

    def dispatch(self, request, *args, **kwargs):
        source_slug = kwargs.pop("source")
        self.source = get_object_or_404(Source, slug=source_slug)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Quote.objects.filter(source=self.source).select_related("source", "source__group").order_by("-created")

    def get_permission_object(self):
        return self.source

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["source"] = self.source
        return context


class QuoteCreateView(LoginRequiredMixin, PermissionRequiredMixin, GenericCreate):
    """
    View for adding a quote to a source.

    Available at /groups/[group_slug]/sources/[source_slug]/quotes/add/
    """

    model = Quote
    template_name = "quotes/quote_create.html"
    permission_required = "django_quotes.edit_source"
    fields = ["quote", "citation", "citation_url", "pub_date"]

    def dispatch(self, request, *args, **kwargs):
        source_slug = kwargs.pop("source")
        self.source = get_object_or_404(Source, slug=source_slug)  # type: ignore
        return super().dispatch(request, *args, **kwargs)

    def get_permission_object(self):
        return self.source

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

django_quotes/templates/quotes/character_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block extratitle %}{{ character.name }} - {% endblock %}
{% block content %}
      <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quotes:group_list' %}">{% translate "Groups" %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quotes:group_detail' group=character.group.slug %}">{{ character.group.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'quotes:character_list' group=character.group.slug %}">{% translate "Characters" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ character.name }}</li>
  </ol>
  </nav>
<h1>{% translate "Character Details" %}: {{ character.name }}</h1>
  <div class="card">
  <h2 class="card-header">{{ character.name }}</h2>
    <div class="card-body">
  {{ character.description_rendered|safe }}
    </div>
    <div class="card-footer text-muted">
  <small>{% translate "Created at" %} {{ character.created }} {% translate "Last modified" %} {{ character.modified }}</small>
    </div>
  </div>
  <p></p>
  <p><a href="{% url 'quotes:character_update' character=character.slug %}" class="btn btn-primary">{% translate "Edit character" %}</a> <a href="{% url "quotes:character_list" group=character.group.slug %}" class="btn btn-secondary">{% translate "Back to character list" %}</a></p>
  <h2>{% translate "Sample of Quotes" %}</h2>
  <table class="table table-striped caption-top">
  <caption>{% translate "Showing" %} {{ samp_quotes|length }} {% translate "of" %} {{ character.quote_set.count }} {% translate "quotes" %}. <a href="{% url 'quotes:quote_list' character=character.slug %}">{% translate "See all." %}</a></caption>
  <thead>
  <tr>
    <th scope="col" class="text-right">#</th>
    <th scope="col">{% translate "Quote" %}</th>
    <th scope="col">{% translate "Cite" %}</th>
    <th scope="col" class="text-end">{% translate "# Times Used" %}</th>
    <th scope="col">{% translate "Tools" %}</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  {% for quote in samp_quotes %}
  <tr>
  <th scope="row" class="text-right"><a href="{% url 'quotes:quote_detail' quote=quote.id %}">{{ quote.id }}</a></th>
  <td>{{ quote.quote_rendered|truncatewords_html:10|safe }}</td>
  <td>
    {% if quote.citation or quote.citation_url %}
    {% if quote.citation_url %}<a href="{{ quote.citation_url }}" target="_blank">{% endif %}{% if quote.citation %}{{ quote.citation }}{% else %}{{ quote.citation_url }}{% endif %}{% if quote.citation_url %}</a>{% endif %}
  {% endif %}
  </td>
  <td class="text-end">{{ quote.stats.times_used }}</td>
    <td><a class="btn btn-primary" href="{% url 'quotes:quote_update' quote=quote.id %}">{% translate "Edit" %}</a></td><td><a href="{% url 'quotes:quote_delete' quote=quote.id %}" class="btn btn-danger">{% translate "Delete" %}</a></td>
  </tr>
  {% empty %}
  {% endfor %}
  </tbody>
  </table>
  <p><a href="{% url 'quotes:quote_create' character=character.slug %}" class="btn btn-success">{% translate "Add new quote" %}</a></p>
  <h2>{% translate "Character Statistics" %}</h2>
  <table class="table">
  <thead>
  <tr>
    <th scope="col" class="text-end">{% translate "Total quotes" %}</th>
    <th scope="col" class="text-end">{% translate "Random quotes requested" %}</th>
    <th scope="col" class="text-end">{% translate "Markov sentences generated" %}</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td class="text-end">{{ character.quote_set.count }}</td>
    <td class="text-end">{{ character.stats.quotes_requested }}</td>
    <td class="text-end">{{ character.stats.quotes_generated }}</td>
  </tr>
  </tbody>
  </table>
  <p class="text-end"><a href="{% url 'quotes:character_delete' character=character.slug %}" class="btn btn-danger">{% translate "Delete character" %}</a></p>
{% endblock %}

django_quotes/templates/quotes/character_group_create.html
{% extends "base.html" %}
{% load i18n crispy_forms_filters %}
{% block extratitle %}{% trans "Create new group" %} - {% endblock %}
{% block content %}
   <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quotes:group_list' %}">{% translate "Groups" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% translate "Add Group" %}</li>
  </ol>
  </nav>
<h1>{% trans "Add new group" %}</h1>
<form method="post" action="">{% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
  <a href="{% url 'quotes:group_list' %}" class="btn btn-secondary">{% trans "Back to list" %}</a>
</form>
{% endblock %}

django_quotes/templates/quotes/character_group_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block extratitle %}{{ group.name }} - {% endblock %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'quotes:group_list' %}">{% translate "Groups" %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ group.name }}</li>
  </ol>
  </nav>
<h1>{% translate "Group Detail" %}: {{ group.name }}</h1>
  <div class="card">
  <h2 class="card-header">{{ group.name }}</h2>
    <div class="card-body">
{{ group.description_rendered|safe }}
      </div>
    <div class="card-footer text-muted">
      <small>{% translate "Created at" %} {{ group.created }} {% translate "Last modified" %} {{ group.modified }}</small>
    </div>
  </div>
  <p></p>
<p>  <a href="{% url 'quotes:group_update' group=group.slug %}" class="btn btn-primary">{% trans "Edit group" %}</a> <a href="{% url 'quotes:group_list' %}" class="btn btn-secondary">{% trans "Back to list" %}</a></p>
  <h2>{% translate "Sample of Characters" %}</h2>
  <table class="table table-striped caption-top">
  <caption>{% translate "Showing" %} {{ char_sample.count }} {% translate "of" %} {{ group.character_set.count }} {% translate "characters." %}
  <a href="{% url 'quotes:character_list' group=group.slug %}">{% translate "See all." %}</a></caption>
  <thead>
  <tr>
    <th scope="col">{% trans "Character" %}</th>
    <th scope="col">{% trans "Allows Markov" %}</th>
    <th scope="col" class="text-end">{% trans "# Quotes" %}</th>
  </tr>
  </thead>
  <tbody>
  {% for char in char_sample %}
  <tr>
    <th scope="row"><a href="{% url 'quotes:character_detail' character=char.slug %}">{{ char.name }}</a></th>
    <td><span class="badge {% if char.allow_markov %}bg-success{% else %}bg-secondary{% endif %}">{% if char.allow_markov %}{% translate "Yes" %}{% else %}{% translate "No" %}{% endif %}</span></td>
    <td class="text-end"><a href="{% url 'quotes:quote_list' character=char.slug %}">{{ char.quote_set.count }}</a></td>
  </tr>
  {% empty %}
  {% endfor %}
  </tbody>
  </table>

  <p><a href="{% url 'quotes:character_create' group=group.slug %}" class="btn btn-success">{% translate "Add new character" %}</a></p>

  <h2>{% translate "Group Statistics" %}</h2>

  <table class="table">
  <thead>
  <tr>
    <th scope="col" class="text-end">{% translate "Total characters" %}</th>
    <th scope="col" class="text-end">{% translate "Total quotes" %}</th>
    <th scope="col" class="text-end">{% translate "Markov enabled characters" %}</th>
    <th scope="col" class="text-end">{% translate "Random quotes requested" %}</th>
    <th scope="col" class="text-end">{% translate "Markov sentences generated" %}</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td class="text-end">{{ group.total_characters }}</td>
    <td class="text-end">{{ group.total_quotes }}</td>
    <td class="text-end">{{ group.markov_characters }}</td>
    <td class="text-end">{{ group.stats.quotes_requested }}</td>
    <td class="text-end">{{ group.stats.quotes_generated }}</td>
  </tr>
  </tbody>
  </table>

  <p class="text-end"><a href="{% url 'quotes:group_delete' group=group.slug %}" class="btn btn-danger">{% trans "Delete group" %}</a></p>
{% endblock %}

django_quotes/templates/quotes/character_group_list.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}
{% block extratitle %}{% trans "Character Groups" %} - {% endblock %}
{% block content %}
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">{% translate "Groups" %}</li>
  </ol>
  </nav>
<h1>{% trans "Your Character Groups" %}</h1>
<table class="table table-striped caption-top">
<caption>{% translate "Showing" %} {{ page_obj|length }} {% translate "of" %} {{ groups.count }}</caption>
<thead>
<tr>
  <th scope="col">{% translate "Group" %}</th>
  <th scope="col">{% translate "Summary" %}</th>
  <th scope="col" class="text-end">{% translate "# Characters" %}</th>
  <th scope="col" class="text-end">{% translate "# Quotes" %}</th>
</tr>
</thead>
<tbody>
  {% for group in page_obj %}
  <tr>
    <th scope="row"><a href="{% url 'quotes:group_detail' group=group.slug %}">{{ group.name }}</a></th>
    <td>{{ group.description_rendered|truncatewords_html:10|safe }}</td>
    <td class="text-end">{{ group.total_characters }}</td>
    <td class="text-end">{{ group.total_quotes }}</td>
  </tr>
  {% empty %}
  {% endfor%}
</tbody>
</table>
  <p><a class="btn btn-success" href="{% url 'quotes:group_create' %}">{% trans "Add new group" %}</a></p>
  {% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">&laquo; {% trans "First" %}</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
    {% endif %}
    <li class="page-item active" aria-current="page"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last" %} &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
  {% endif %}
{% endblock %}